# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index(object):
    def setupUi(self, index):
        index.setObjectName("index")
        index.resize(1000, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(index.sizePolicy().hasHeightForWidth())
        index.setSizePolicy(sizePolicy)
        index.setMinimumSize(QtCore.QSize(1000, 618))
        index.setMaximumSize(QtCore.QSize(1000, 618))
        index.setStyleSheet("background-color:rgb(224, 242, 255);\n"
"border: none;\n"
"font: 16px \"微软雅黑\";\n"
"color: #333333\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(index)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left = QtWidgets.QFrame(index)
        self.left.setStyleSheet("\n"
"background-color:#2B579A;\n"
"text-align: left;")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.leftTop = QtWidgets.QFrame(self.left)
        self.leftTop.setGeometry(QtCore.QRect(0, 0, 240, 80))
        self.leftTop.setStyleSheet("background-color:#41A5EE;")
        self.leftTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftTop.setObjectName("leftTop")
        self.headImg = QtWidgets.QLabel(self.leftTop)
        self.headImg.setGeometry(QtCore.QRect(16, 20, 40, 40))
        self.headImg.setMinimumSize(QtCore.QSize(40, 40))
        self.headImg.setMaximumSize(QtCore.QSize(40, 40))
        self.headImg.setStyleSheet("border-radius: 20px;\n"
"background-color: #fff;")
        self.headImg.setText("")
        self.headImg.setObjectName("headImg")
        self.uerName = QtWidgets.QLabel(self.leftTop)
        self.uerName.setGeometry(QtCore.QRect(68, 28, 71, 25))
        self.uerName.setMinimumSize(QtCore.QSize(0, 25))
        self.uerName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.uerName.setStyleSheet("background-color:#41A5EE;")
        self.uerName.setTextFormat(QtCore.Qt.PlainText)
        self.uerName.setObjectName("uerName")
        self.setButton = QtWidgets.QToolButton(self.leftTop)
        self.setButton.setGeometry(QtCore.QRect(208, 28, 24, 24))
        self.setButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setButton.setStyleSheet("QToolButton {\n"
"background-color: none;\n"
"image: url(:/open/img/open/Setting_open_unselected.png)\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    image: url(:/selected/img/selected/Setting_selected.png);\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    image: url(:/selected/img/selected/Setting_selected.png);\n"
"}")
        self.setButton.setText("")
        self.setButton.setObjectName("setButton")
        self.kp = QtWidgets.QFrame(self.left)
        self.kp.setGeometry(QtCore.QRect(8, 104, 224, 40))
        self.kp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp.setStyleSheet("")
        self.kp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kp.setObjectName("kp")
        self.kpButton = QtWidgets.QPushButton(self.kp)
        self.kpButton.setGeometry(QtCore.QRect(0, 0, 224, 40))
        self.kpButton.setMinimumSize(QtCore.QSize(224, 40))
        self.kpButton.setMaximumSize(QtCore.QSize(224, 40))
        self.kpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kpButton.setStyleSheet("QPushButton{\n"
"    background-color: #93D2FF;\n"
"    border-radius: 14px;\n"
"    padding:46px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.kpButton.setCheckable(True)
        self.kpButton.setObjectName("kpButton")
        self.kpIcon = QtWidgets.QLabel(self.kp)
        self.kpIcon.setGeometry(QtCore.QRect(16, 10, 24, 21))
        self.kpIcon.setStyleSheet("image: url(:/open/img/open/Chat_open_unselected.png);\n"
"background-color: none;")
        self.kpIcon.setText("")
        self.kpIcon.setObjectName("kpIcon")
        self.pm = QtWidgets.QFrame(self.left)
        self.pm.setGeometry(QtCore.QRect(8, 164, 224, 40))
        self.pm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pm.setStyleSheet("")
        self.pm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pm.setObjectName("pm")
        self.pmButton = QtWidgets.QPushButton(self.pm)
        self.pmButton.setGeometry(QtCore.QRect(0, 0, 224, 40))
        self.pmButton.setMinimumSize(QtCore.QSize(224, 40))
        self.pmButton.setMaximumSize(QtCore.QSize(224, 40))
        self.pmButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pmButton.setStyleSheet("QPushButton{\n"
"    background-color: #93D2FF;\n"
"    border-radius: 14px;\n"
"    padding:46px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.pmButton.setCheckable(True)
        self.pmButton.setObjectName("pmButton")
        self.pmIcon = QtWidgets.QLabel(self.pm)
        self.pmIcon.setGeometry(QtCore.QRect(16, 10, 24, 21))
        self.pmIcon.setStyleSheet("image: url(:/open/img/open/Rank_open_unselected.png);\n"
"background-color: none;")
        self.pmIcon.setText("")
        self.pmIcon.setObjectName("pmIcon")
        self.sc = QtWidgets.QFrame(self.left)
        self.sc.setGeometry(QtCore.QRect(8, 284, 224, 40))
        self.sc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sc.setObjectName("sc")
        self.scButton = QtWidgets.QPushButton(self.sc)
        self.scButton.setGeometry(QtCore.QRect(0, 0, 224, 40))
        self.scButton.setMinimumSize(QtCore.QSize(224, 40))
        self.scButton.setMaximumSize(QtCore.QSize(224, 40))
        self.scButton.setStyleSheet("QPushButton{\n"
"    background-color: #93D2FF;\n"
"    border-radius: 14px;\n"
"    padding:46px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.scButton.setCheckable(True)
        self.scButton.setObjectName("scButton")
        self.scIcon = QtWidgets.QLabel(self.sc)
        self.scIcon.setGeometry(QtCore.QRect(16, 10, 24, 21))
        self.scIcon.setStyleSheet("image: url(:/open/img/open/Collect_open_unselected.png);\n"
"background-color: none;")
        self.scIcon.setText("")
        self.scIcon.setObjectName("scIcon")
        self.qk = QtWidgets.QFrame(self.left)
        self.qk.setGeometry(QtCore.QRect(8, 224, 224, 40))
        self.qk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qk.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qk.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qk.setObjectName("qk")
        self.tjButton = QtWidgets.QPushButton(self.qk)
        self.tjButton.setGeometry(QtCore.QRect(0, 0, 224, 40))
        self.tjButton.setMinimumSize(QtCore.QSize(224, 40))
        self.tjButton.setMaximumSize(QtCore.QSize(224, 40))
        self.tjButton.setStyleSheet("QPushButton{\n"
"    background-color: #93D2FF;\n"
"    border-radius: 14px;\n"
"    padding:46px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"")
        self.tjButton.setCheckable(True)
        self.tjButton.setObjectName("tjButton")
        self.thIcon = QtWidgets.QLabel(self.qk)
        self.thIcon.setGeometry(QtCore.QRect(16, 10, 24, 21))
        self.thIcon.setStyleSheet("image: url(:/open/img/open/Study_open_unselected.png);\n"
"background-color: none;")
        self.thIcon.setText("")
        self.thIcon.setObjectName("thIcon")
        self.putAwayButton = QtWidgets.QToolButton(self.left)
        self.putAwayButton.setGeometry(QtCore.QRect(200, 580, 28, 28))
        self.putAwayButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.putAwayButton.setStyleSheet("image: url(:/chatting/img/Chatting/turnleft.png);")
        self.putAwayButton.setText("")
        self.putAwayButton.setObjectName("putAwayButton")
        self.horizontalLayout.addWidget(self.left)
        self.right = QtWidgets.QFrame(index)
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.minimizeButton = QtWidgets.QToolButton(self.right)
        self.minimizeButton.setGeometry(QtCore.QRect(690, 10, 20, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/frame/img/Frame/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon)
        self.minimizeButton.setObjectName("minimizeButton")
        self.closeButton = QtWidgets.QToolButton(self.right)
        self.closeButton.setGeometry(QtCore.QRect(730, 10, 20, 20))
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/frame/img/Frame/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setObjectName("closeButton")
        self.right_pm = QtWidgets.QFrame(self.right)
        self.right_pm.setGeometry(QtCore.QRect(0, 0, 760, 618))
        self.right_pm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_pm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_pm.setObjectName("right_pm")
        self.winTitle_pm = QtWidgets.QLabel(self.right_pm)
        self.winTitle_pm.setGeometry(QtCore.QRect(0, 0, 760, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.winTitle_pm.setFont(font)
        self.winTitle_pm.setStyleSheet("font-size:32px;font-weight: 700;")
        self.winTitle_pm.setAlignment(QtCore.Qt.AlignCenter)
        self.winTitle_pm.setObjectName("winTitle_pm")
        self.pm_myLearnTime = QtWidgets.QFrame(self.right_pm)
        self.pm_myLearnTime.setGeometry(QtCore.QRect(121, 112, 120, 120))
        self.pm_myLearnTime.setStyleSheet("background-color:#fff;\n"
"border-radius: 60px;")
        self.pm_myLearnTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pm_myLearnTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pm_myLearnTime.setObjectName("pm_myLearnTime")
        self.pm_mlt_title = QtWidgets.QLabel(self.pm_myLearnTime)
        self.pm_mlt_title.setGeometry(QtCore.QRect(0, 0, 120, 60))
        self.pm_mlt_title.setStyleSheet("background-color: none;\n"
"font-size: 20px;\n"
"color: #4A7CC6;\n"
"font-weight: 500;")
        self.pm_mlt_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.pm_mlt_title.setObjectName("pm_mlt_title")
        self.pm_mlt_detail = QtWidgets.QLabel(self.pm_myLearnTime)
        self.pm_mlt_detail.setGeometry(QtCore.QRect(0, 60, 120, 60))
        self.pm_mlt_detail.setStyleSheet("background-color: none;\n"
"font-size: 16px;\n"
"")
        self.pm_mlt_detail.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pm_mlt_detail.setObjectName("pm_mlt_detail")
        self.pm_myRank = QtWidgets.QFrame(self.right_pm)
        self.pm_myRank.setGeometry(QtCore.QRect(321, 112, 120, 120))
        self.pm_myRank.setStyleSheet("background-color:#fff;\n"
"border-radius: 60px;")
        self.pm_myRank.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pm_myRank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pm_myRank.setObjectName("pm_myRank")
        self.pm_mr_title = QtWidgets.QLabel(self.pm_myRank)
        self.pm_mr_title.setGeometry(QtCore.QRect(0, 0, 120, 60))
        self.pm_mr_title.setStyleSheet("background-color: none;\n"
"font-size: 20px;\n"
"color: #FF6D00;\n"
"font-weight: 500;")
        self.pm_mr_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.pm_mr_title.setObjectName("pm_mr_title")
        self.pm_mr_detail = QtWidgets.QLabel(self.pm_myRank)
        self.pm_mr_detail.setGeometry(QtCore.QRect(0, 60, 120, 60))
        self.pm_mr_detail.setStyleSheet("background-color: none;\n"
"font-size: 16px;\n"
"")
        self.pm_mr_detail.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pm_mr_detail.setObjectName("pm_mr_detail")
        self.pm_myScore = QtWidgets.QFrame(self.right_pm)
        self.pm_myScore.setGeometry(QtCore.QRect(490, 110, 120, 120))
        self.pm_myScore.setStyleSheet("background-color:#fff;\n"
"border-radius: 60px;")
        self.pm_myScore.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pm_myScore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pm_myScore.setObjectName("pm_myScore")
        self.pm_ms_title = QtWidgets.QLabel(self.pm_myScore)
        self.pm_ms_title.setGeometry(QtCore.QRect(0, 0, 120, 60))
        self.pm_ms_title.setStyleSheet("background-color: none;\n"
"font-size: 20px;\n"
"color: #4A7CC6;\n"
"font-weight: 500;")
        self.pm_ms_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.pm_ms_title.setObjectName("pm_ms_title")
        self.pm_ms_detail = QtWidgets.QLabel(self.pm_myScore)
        self.pm_ms_detail.setGeometry(QtCore.QRect(0, 60, 120, 60))
        self.pm_ms_detail.setStyleSheet("background-color: none;\n"
"font-size: 16px;\n"
"")
        self.pm_ms_detail.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pm_ms_detail.setObjectName("pm_ms_detail")
        self.pm_rankList = QtWidgets.QScrollArea(self.right_pm)
        self.pm_rankList.setGeometry(QtCore.QRect(0, 275, 760, 340))
        self.pm_rankList.setWidgetResizable(True)
        self.pm_rankList.setObjectName("pm_rankList")
        self.pm_rl_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.pm_rl_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 340))
        self.pm_rl_scrollAreaWidgetContents.setStyleSheet("")
        self.pm_rl_scrollAreaWidgetContents.setObjectName("pm_rl_scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pm_rl_scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(15, 0, 15, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pm_rl_rankDetail = QtWidgets.QFrame(self.pm_rl_scrollAreaWidgetContents)
        self.pm_rl_rankDetail.setStyleSheet("background-color: #FFF;\n"
"border-radius: 12px;\n"
"")
        self.pm_rl_rankDetail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pm_rl_rankDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pm_rl_rankDetail.setObjectName("pm_rl_rankDetail")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pm_rl_rankDetail)
        self.horizontalLayout_4.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pm_rl_rd_rank = QtWidgets.QLabel(self.pm_rl_rankDetail)
        self.pm_rl_rd_rank.setStyleSheet("margin:0 0;")
        self.pm_rl_rd_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.pm_rl_rd_rank.setObjectName("pm_rl_rd_rank")
        self.horizontalLayout_4.addWidget(self.pm_rl_rd_rank)
        self.pm_rl_rd_Img = QtWidgets.QPushButton(self.pm_rl_rankDetail)
        self.pm_rl_rd_Img.setMinimumSize(QtCore.QSize(40, 40))
        self.pm_rl_rd_Img.setStyleSheet("margin:0 0;\n"
"background-color: #93D2FF;\n"
"border-radius: 20px")
        self.pm_rl_rd_Img.setText("")
        self.pm_rl_rd_Img.setIconSize(QtCore.QSize(60, 60))
        self.pm_rl_rd_Img.setObjectName("pm_rl_rd_Img")
        self.horizontalLayout_4.addWidget(self.pm_rl_rd_Img)
        self.pm_rl_rd_name = QtWidgets.QLabel(self.pm_rl_rankDetail)
        self.pm_rl_rd_name.setStyleSheet("margin:0 0;")
        self.pm_rl_rd_name.setObjectName("pm_rl_rd_name")
        self.horizontalLayout_4.addWidget(self.pm_rl_rd_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pm_rl_rd_learnTime = QtWidgets.QLabel(self.pm_rl_rankDetail)
        self.pm_rl_rd_learnTime.setStyleSheet("margin:0 0;")
        self.pm_rl_rd_learnTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pm_rl_rd_learnTime.setObjectName("pm_rl_rd_learnTime")
        self.horizontalLayout_4.addWidget(self.pm_rl_rd_learnTime)
        self.pm_rl_rd_score = QtWidgets.QLabel(self.pm_rl_rankDetail)
        self.pm_rl_rd_score.setStyleSheet("margin:0 0;")
        self.pm_rl_rd_score.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pm_rl_rd_score.setObjectName("pm_rl_rd_score")
        self.horizontalLayout_4.addWidget(self.pm_rl_rd_score)
        self.verticalLayout_2.addWidget(self.pm_rl_rankDetail)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pm_rankList.setWidget(self.pm_rl_scrollAreaWidgetContents)
        self.right_tj = QtWidgets.QFrame(self.right)
        self.right_tj.setGeometry(QtCore.QRect(0, 0, 760, 618))
        self.right_tj.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_tj.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_tj.setObjectName("right_tj")
        self.winTitle_tj = QtWidgets.QLabel(self.right_tj)
        self.winTitle_tj.setGeometry(QtCore.QRect(0, 0, 760, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.winTitle_tj.setFont(font)
        self.winTitle_tj.setStyleSheet("font-size:32px;\n"
"font-weight: 700;")
        self.winTitle_tj.setAlignment(QtCore.Qt.AlignCenter)
        self.winTitle_tj.setObjectName("winTitle_tj")
        self.tj_times = QtWidgets.QFrame(self.right_tj)
        self.tj_times.setGeometry(QtCore.QRect(78, 116, 160, 160))
        self.tj_times.setStyleSheet("background-color:#fff;\n"
"border-radius: 20px;")
        self.tj_times.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tj_times.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tj_times.setObjectName("tj_times")
        self.tj_t_title = QtWidgets.QLabel(self.tj_times)
        self.tj_t_title.setGeometry(QtCore.QRect(0, 10, 160, 40))
        self.tj_t_title.setStyleSheet("font-size: 20px;\n"
"backgroun-color: none;\n"
"color: #2B579A;\n"
"font-weight: 500")
        self.tj_t_title.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_t_title.setObjectName("tj_t_title")
        self.tj_t_detail = QtWidgets.QLabel(self.tj_times)
        self.tj_t_detail.setGeometry(QtCore.QRect(0, 40, 160, 120))
        self.tj_t_detail.setStyleSheet("font-size: 72px;\n"
"backgroun-color: none;\n"
"font-weight: 500;")
        self.tj_t_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_t_detail.setObjectName("tj_t_detail")
        self.tj_t_detail.raise_()
        self.tj_t_title.raise_()
        self.tj_learnTime = QtWidgets.QFrame(self.right_tj)
        self.tj_learnTime.setGeometry(QtCore.QRect(300, 116, 160, 160))
        self.tj_learnTime.setStyleSheet("background-color:#fff;\n"
"border-radius: 20px;")
        self.tj_learnTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tj_learnTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tj_learnTime.setObjectName("tj_learnTime")
        self.tj_lt_detail = QtWidgets.QLabel(self.tj_learnTime)
        self.tj_lt_detail.setGeometry(QtCore.QRect(0, 40, 160, 120))
        self.tj_lt_detail.setStyleSheet("font-size: 24px;\n"
"backgroun-color: none;\n"
"")
        self.tj_lt_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_lt_detail.setObjectName("tj_lt_detail")
        self.tj_lt_title = QtWidgets.QLabel(self.tj_learnTime)
        self.tj_lt_title.setGeometry(QtCore.QRect(0, 10, 160, 40))
        self.tj_lt_title.setStyleSheet("font-size: 20px;\n"
"backgroun-color: none;\n"
"color: #2B579A;\n"
"font-weight: 500;")
        self.tj_lt_title.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_lt_title.setObjectName("tj_lt_title")
        self.tj_score = QtWidgets.QFrame(self.right_tj)
        self.tj_score.setGeometry(QtCore.QRect(522, 116, 160, 160))
        self.tj_score.setStyleSheet("background-color:#fff;\n"
"border-radius: 20px;")
        self.tj_score.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tj_score.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tj_score.setObjectName("tj_score")
        self.tj_s_detail = QtWidgets.QLabel(self.tj_score)
        self.tj_s_detail.setGeometry(QtCore.QRect(0, 40, 160, 120))
        self.tj_s_detail.setStyleSheet("font-size: 72px;\n"
"backgroun-color: none;\n"
"font-weight: 500;")
        self.tj_s_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_s_detail.setObjectName("tj_s_detail")
        self.tj_s_title = QtWidgets.QLabel(self.tj_score)
        self.tj_s_title.setGeometry(QtCore.QRect(0, 10, 160, 40))
        self.tj_s_title.setStyleSheet("font-size: 20px;\n"
"backgroun-color: none;\n"
"color: #2B579A;\n"
"font-weight: 500;")
        self.tj_s_title.setAlignment(QtCore.Qt.AlignCenter)
        self.tj_s_title.setObjectName("tj_s_title")
        self.tj_statistics = QtWidgets.QScrollArea(self.right_tj)
        self.tj_statistics.setGeometry(QtCore.QRect(0, 312, 760, 306))
        self.tj_statistics.setWidgetResizable(True)
        self.tj_statistics.setObjectName("tj_statistics")
        self.tj_s_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.tj_s_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 306))
        self.tj_s_scrollAreaWidgetContents.setStyleSheet("")
        self.tj_s_scrollAreaWidgetContents.setObjectName("tj_s_scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tj_s_scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tj_s_Detail = QtWidgets.QFrame(self.tj_s_scrollAreaWidgetContents)
        self.tj_s_Detail.setStyleSheet("background-color: #FFF;\n"
"border-radius: 12px;\n"
"")
        self.tj_s_Detail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tj_s_Detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tj_s_Detail.setObjectName("tj_s_Detail")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tj_s_Detail)
        self.horizontalLayout_5.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tj_s_d_img = QtWidgets.QPushButton(self.tj_s_Detail)
        self.tj_s_d_img.setMinimumSize(QtCore.QSize(40, 40))
        self.tj_s_d_img.setStyleSheet("margin:0 0;\n"
"background-color: #93D2FF;\n"
"border-radius: 20px")
        self.tj_s_d_img.setText("")
        self.tj_s_d_img.setIconSize(QtCore.QSize(60, 60))
        self.tj_s_d_img.setObjectName("tj_s_d_img")
        self.horizontalLayout_5.addWidget(self.tj_s_d_img)
        self.tj_s_d_name = QtWidgets.QLabel(self.tj_s_Detail)
        self.tj_s_d_name.setStyleSheet("margin:0 0;")
        self.tj_s_d_name.setObjectName("tj_s_d_name")
        self.horizontalLayout_5.addWidget(self.tj_s_d_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.tj_s_d_learnTime = QtWidgets.QLabel(self.tj_s_Detail)
        self.tj_s_d_learnTime.setStyleSheet("margin:0 0;")
        self.tj_s_d_learnTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tj_s_d_learnTime.setObjectName("tj_s_d_learnTime")
        self.horizontalLayout_5.addWidget(self.tj_s_d_learnTime)
        self.verticalLayout_4.addWidget(self.tj_s_Detail)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tj_statistics.setWidget(self.tj_s_scrollAreaWidgetContents)
        self.right_sc = QtWidgets.QFrame(self.right)
        self.right_sc.setGeometry(QtCore.QRect(0, 0, 760, 618))
        self.right_sc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_sc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_sc.setObjectName("right_sc")
        self.winTitle_sc = QtWidgets.QLabel(self.right_sc)
        self.winTitle_sc.setGeometry(QtCore.QRect(0, 0, 760, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.winTitle_sc.setFont(font)
        self.winTitle_sc.setStyleSheet("font-size:32px;\n"
"font-weight: 700;")
        self.winTitle_sc.setAlignment(QtCore.Qt.AlignCenter)
        self.winTitle_sc.setObjectName("winTitle_sc")
        self.sc_search = QtWidgets.QFrame(self.right_sc)
        self.sc_search.setGeometry(QtCore.QRect(20, 96, 720, 48))
        self.sc_search.setStyleSheet("border-radius: 16px;\n"
"background-color: #ffffff;")
        self.sc_search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sc_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sc_search.setObjectName("sc_search")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.sc_search)
        self.hboxlayout.setContentsMargins(15, 0, 15, 0)
        self.hboxlayout.setSpacing(15)
        self.hboxlayout.setObjectName("hboxlayout")
        self.sc_s_icon = QtWidgets.QLabel(self.sc_search)
        self.sc_s_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.sc_s_icon.setStyleSheet("image: url(:/collect/img/Collect/search.png);")
        self.sc_s_icon.setText("")
        self.sc_s_icon.setObjectName("sc_s_icon")
        self.hboxlayout.addWidget(self.sc_s_icon)
        self.sc_s_input = QtWidgets.QTextEdit(self.sc_search)
        self.sc_s_input.setMinimumSize(QtCore.QSize(0, 48))
        self.sc_s_input.setMaximumSize(QtCore.QSize(16777215, 48))
        self.sc_s_input.setStyleSheet("padding:10px 0;")
        self.sc_s_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sc_s_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sc_s_input.setObjectName("sc_s_input")
        self.hboxlayout.addWidget(self.sc_s_input)
        self.sc_s_searchButton = QtWidgets.QPushButton(self.sc_search)
        self.sc_s_searchButton.setObjectName("sc_s_searchButton")
        self.hboxlayout.addWidget(self.sc_s_searchButton)
        self.sc_collectDetail = QtWidgets.QScrollArea(self.right_sc)
        self.sc_collectDetail.setGeometry(QtCore.QRect(0, 160, 760, 455))
        self.sc_collectDetail.setMinimumSize(QtCore.QSize(0, 0))
        self.sc_collectDetail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sc_collectDetail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sc_collectDetail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sc_collectDetail.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.sc_collectDetail.setWidgetResizable(True)
        self.sc_collectDetail.setObjectName("sc_collectDetail")
        self.sc_cd_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.sc_cd_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 455))
        self.sc_cd_scrollAreaWidgetContents.setObjectName("sc_cd_scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sc_cd_scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(20, 0, 20, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sc_cd_detail = QtWidgets.QFrame(self.sc_cd_scrollAreaWidgetContents)
        self.sc_cd_detail.setMinimumSize(QtCore.QSize(720, 120))
        self.sc_cd_detail.setStyleSheet("background-color: #fff;\n"
"border-radius: 16px;\n"
"margin-buttom: 20px")
        self.sc_cd_detail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sc_cd_detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sc_cd_detail.setObjectName("sc_cd_detail")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.sc_cd_detail)
        self.horizontalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sc_cd_d_img = QtWidgets.QLabel(self.sc_cd_detail)
        self.sc_cd_d_img.setMinimumSize(QtCore.QSize(80, 80))
        self.sc_cd_d_img.setStyleSheet("background-color: #93D2FF;\n"
"border-radius:10px")
        self.sc_cd_d_img.setText("")
        self.sc_cd_d_img.setObjectName("sc_cd_d_img")
        self.horizontalLayout_6.addWidget(self.sc_cd_d_img)
        self.sc_cd_d_title = QtWidgets.QLabel(self.sc_cd_detail)
        self.sc_cd_d_title.setObjectName("sc_cd_d_title")
        self.horizontalLayout_6.addWidget(self.sc_cd_d_title)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.sc_cd_d_collectButton = QtWidgets.QToolButton(self.sc_cd_detail)
        self.sc_cd_d_collectButton.setMinimumSize(QtCore.QSize(28, 28))
        self.sc_cd_d_collectButton.setStyleSheet("QToolButton {\n"
"    image: url(:/collect/img/Collect/Collect_selected.png);\n"
"}\n"
"QToolButton:hover {\n"
"    image: url(:/collect/img/Collect/Collect_unselected.png);\n"
"}\n"
"QToolButton:checked {\n"
"    image: url(:/collect/img/Collect/Collect_unselected.png);\n"
"}")
        self.sc_cd_d_collectButton.setText("")
        self.sc_cd_d_collectButton.setCheckable(True)
        self.sc_cd_d_collectButton.setObjectName("sc_cd_d_collectButton")
        self.horizontalLayout_6.addWidget(self.sc_cd_d_collectButton)
        self.verticalLayout_3.addWidget(self.sc_cd_detail)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.sc_collectDetail.setWidget(self.sc_cd_scrollAreaWidgetContents)
        self.right_kp = QtWidgets.QFrame(self.right)
        self.right_kp.setGeometry(QtCore.QRect(0, 0, 760, 618))
        self.right_kp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_kp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_kp.setObjectName("right_kp")
        self.kp_inputFrame = QtWidgets.QFrame(self.right_kp)
        self.kp_inputFrame.setGeometry(QtCore.QRect(0, 450, 760, 168))
        self.kp_inputFrame.setStyleSheet("background-color:rgb(224, 242, 255);\n"
"\n"
"")
        self.kp_inputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kp_inputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kp_inputFrame.setObjectName("kp_inputFrame")
        self.kp_if_microphone = QtWidgets.QToolButton(self.kp_inputFrame)
        self.kp_if_microphone.setGeometry(QtCore.QRect(330, 34, 100, 100))
        self.kp_if_microphone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_if_microphone.setStyleSheet("image: url(:/chatting/img/Chatting/microphone2.png);")
        self.kp_if_microphone.setText("")
        self.kp_if_microphone.setObjectName("kp_if_microphone")
        self.kp_if_write = QtWidgets.QFrame(self.kp_inputFrame)
        self.kp_if_write.setGeometry(QtCore.QRect(0, 0, 760, 168))
        self.kp_if_write.setStyleSheet("background-color: #fff;")
        self.kp_if_write.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kp_if_write.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kp_if_write.setObjectName("kp_if_write")
        self.kp_if_w_sendEdit = QtWidgets.QTextEdit(self.kp_if_write)
        self.kp_if_w_sendEdit.setGeometry(QtCore.QRect(0, 42, 760, 126))
        self.kp_if_w_sendEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.kp_if_w_sendEdit.setStyleSheet("padding-left: 10px;\n"
"padding-right: 10px;\n"
"")
        self.kp_if_w_sendEdit.setObjectName("kp_if_w_sendEdit")
        self.kp_if_w_emoji = QtWidgets.QToolButton(self.kp_if_write)
        self.kp_if_w_emoji.setGeometry(QtCore.QRect(15, 10, 25, 25))
        self.kp_if_w_emoji.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_if_w_emoji.setStyleSheet("image: url(:/chatting/img/Chatting/smile.png);")
        self.kp_if_w_emoji.setText("")
        self.kp_if_w_emoji.setObjectName("kp_if_w_emoji")
        self.kp_if_w_send = QtWidgets.QPushButton(self.kp_if_write)
        self.kp_if_w_send.setGeometry(QtCore.QRect(686, 10, 64, 32))
        self.kp_if_w_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_if_w_send.setStyleSheet("QPushButton{\n"
"    background-color: #93D2FF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #2B579A;\n"
"    color:#fff;\n"
"}\n"
"\n"
"")
        self.kp_if_w_send.setObjectName("kp_if_w_send")
        self.kp_if_w_speak = QtWidgets.QToolButton(self.kp_if_write)
        self.kp_if_w_speak.setGeometry(QtCore.QRect(50, 10, 25, 25))
        self.kp_if_w_speak.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_if_w_speak.setStyleSheet("image: url(:/chatting/img/Chatting/microphone.png);")
        self.kp_if_w_speak.setText("")
        self.kp_if_w_speak.setObjectName("kp_if_w_speak")
        self.kp_if_writeButton = QtWidgets.QToolButton(self.kp_inputFrame)
        self.kp_if_writeButton.setGeometry(QtCore.QRect(720, 130, 20, 20))
        self.kp_if_writeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_if_writeButton.setStyleSheet("image: url(:/chatting/img/Chatting/type.png);")
        self.kp_if_writeButton.setText("")
        self.kp_if_writeButton.setObjectName("kp_if_writeButton")
        self.kp_if_writeButton.raise_()
        self.kp_if_microphone.raise_()
        self.kp_if_write.raise_()
        self.kp_changeButton = QtWidgets.QToolButton(self.right_kp)
        self.kp_changeButton.setGeometry(QtCore.QRect(720, 50, 20, 20))
        self.kp_changeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kp_changeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/chatting/img/Chatting/exchange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kp_changeButton.setIcon(icon2)
        self.kp_changeButton.setObjectName("kp_changeButton")
        self.kp_chatArea = QtWidgets.QScrollArea(self.right_kp)
        self.kp_chatArea.setGeometry(QtCore.QRect(0, 80, 760, 370))
        self.kp_chatArea.setMaximumSize(QtCore.QSize(760, 16777215))
        self.kp_chatArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.kp_chatArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.kp_chatArea.setWidgetResizable(True)
        self.kp_chatArea.setObjectName("kp_chatArea")
        self.kp_ca_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.kp_ca_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 370))
        self.kp_ca_scrollAreaWidgetContents.setObjectName("kp_ca_scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.kp_ca_scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.kp_chatArea.setWidget(self.kp_ca_scrollAreaWidgetContents)
        self.winTitle_kp = QtWidgets.QLabel(self.right_kp)
        self.winTitle_kp.setGeometry(QtCore.QRect(0, 0, 760, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.winTitle_kp.setFont(font)
        self.winTitle_kp.setStyleSheet("font-size:32px;\n"
"font-weight: 700;")
        self.winTitle_kp.setAlignment(QtCore.Qt.AlignCenter)
        self.winTitle_kp.setObjectName("winTitle_kp")
        self.kp_inputFrame.raise_()
        self.kp_chatArea.raise_()
        self.winTitle_kp.raise_()
        self.kp_changeButton.raise_()
        self.right_pm.raise_()
        self.right_sc.raise_()
        self.right_tj.raise_()
        self.right_kp.raise_()
        self.closeButton.raise_()
        self.minimizeButton.raise_()
        self.horizontalLayout.addWidget(self.right)
        self.horizontalLayout.setStretch(0, 24)
        self.horizontalLayout.setStretch(1, 76)

        self.retranslateUi(index)
        self.closeButton.clicked.connect(index.close)
        self.minimizeButton.clicked.connect(index.showMinimized)
        self.pmButton.clicked.connect(self.right_pm.show)
        self.pmButton.clicked.connect(self.right_kp.close)
        self.pmButton.clicked.connect(self.right_sc.close)
        self.pmButton.clicked.connect(self.right_tj.close)
        self.tjButton.clicked.connect(self.right_tj.show)
        self.scButton.clicked.connect(self.right_tj.close)
        self.kpButton.clicked.connect(self.right_tj.close)
        self.scButton.clicked.connect(self.right_sc.show)
        self.tjButton.clicked.connect(self.right_sc.close)
        self.kpButton.clicked.connect(self.right_sc.close)
        self.kpButton.clicked.connect(self.right_pm.close)
        self.tjButton.clicked.connect(self.right_pm.close)
        self.kpButton.clicked.connect(self.right_kp.show)
        self.scButton.clicked.connect(self.right_kp.close)
        self.scButton.clicked.connect(self.right_pm.close)
        self.tjButton.clicked.connect(self.right_kp.close)
        self.kp_if_w_speak.clicked.connect(self.kp_if_microphone.show)
        self.kp_if_writeButton.clicked.connect(self.kp_if_write.show)
        self.kp_if_writeButton.clicked.connect(self.kp_if_microphone.close)
        self.kp_if_w_speak.clicked.connect(self.kp_if_write.close)
        self.kp_if_writeButton.clicked.connect(self.kp_if_writeButton.close)
        self.kp_if_w_speak.clicked.connect(self.kp_if_writeButton.show)
        QtCore.QMetaObject.connectSlotsByName(index)

    def retranslateUi(self, index):
        _translate = QtCore.QCoreApplication.translate
        index.setWindowTitle(_translate("index", "Form"))
        self.uerName.setText(_translate("index", "用户名"))
        self.kpButton.setText(_translate("index", "科普聊天"))
        self.pmButton.setText(_translate("index", "排名"))
        self.scButton.setText(_translate("index", "收藏"))
        self.tjButton.setText(_translate("index", "统计"))
        self.minimizeButton.setText(_translate("index", "..."))
        self.winTitle_pm.setText(_translate("index", "排   名"))
        self.pm_mlt_title.setText(_translate("index", "学习时长"))
        self.pm_mlt_detail.setText(_translate("index", "24小时56分"))
        self.pm_mr_title.setText(_translate("index", "当前排名"))
        self.pm_mr_detail.setText(_translate("index", "2"))
        self.pm_ms_title.setText(_translate("index", "我的积分"))
        self.pm_ms_detail.setText(_translate("index", "300"))
        self.pm_rl_rd_rank.setText(_translate("index", "1"))
        self.pm_rl_rd_name.setText(_translate("index", "apple"))
        self.pm_rl_rd_learnTime.setText(_translate("index", "24小时56分"))
        self.pm_rl_rd_score.setText(_translate("index", "300分"))
        self.winTitle_tj.setText(_translate("index", "统   计"))
        self.tj_t_title.setText(_translate("index", "今日学习次数"))
        self.tj_t_detail.setText(_translate("index", "33"))
        self.tj_lt_detail.setText(_translate("index", "1小时8分"))
        self.tj_lt_title.setText(_translate("index", "今日学习时长"))
        self.tj_s_detail.setText(_translate("index", "68"))
        self.tj_s_title.setText(_translate("index", "今日获得积分"))
        self.tj_s_d_name.setText(_translate("index", "苹果的一百种吃法"))
        self.tj_s_d_learnTime.setText(_translate("index", "0小时56分"))
        self.winTitle_sc.setText(_translate("index", "收   藏"))
        self.sc_s_input.setHtml(_translate("index", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">    </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:48px; background-color:#7fffd4;\"><br /></p></body></html>"))
        self.sc_s_searchButton.setText(_translate("index", "搜索"))
        self.sc_cd_d_title.setText(_translate("index", "苹果的一百种吃法"))
        self.kp_if_w_send.setText(_translate("index", "发送"))
        self.winTitle_kp.setText(_translate("index", "科   科"))
import resource_rc
